### ISSUE TITLE
Rendering the editor breaks the current body overflow

### ISSUE THREAD

**Issue by nuragic** [uiwjs/react-md-editor#309]
Hi,

First of all, thanks so much for this amazing lib! 🙌 

I just found out that This line is causing problems because it changes the `body` styles directly by setting the overflow to either `initial` or `hidden`.

https://github.com/uiwjs/react-md-editor/blob/master/src/components/Toolbar/index.tsx#L49

Imagine we have a fixed body layout and we always want the overflow to be hidden... we can't basically use this component.

I could open a PR to fix it but I don't know really which approach would be better... any preference?

Thanks!

**Comment by jaywcjlove** [comment]
@nuragic This is a full screen feature. Can it be solved by style override?

```css
body {
    overflow: auto !important;
    overflow-x: auto !important;;
}
```

**Comment by nuragic** [comment]
@jaywcjlove Unfortunately no, not in this case. I illustrated a simple example above, but in reality we manage some views inside modals, so the "modal manager" is the responsible from changing the body overflow when needed. We do not own that code, we use a UI library that handles that. This causes unexpected bugs, e.g the double scroll on both modal body and document body. We don't want the document body overflow to be touched, we don't even use `fullscreen`. That's a key part: this logic must not be run when that prop is unset, IMHO. I guess that it would be one friendly and backwards compatible way to solve this problem. Would be that ok for you?

**Comment by nuragic** [comment]
Things to take in mind for anyone who would try to solve this issue:

- the component should run this logic only when fullscreen is set to true (should not run any effect if the editor is being  rendered not on fullscreen)
- the initial body overflow must be respected, so don't assume that "initial" would work, just get the actual body styles first
- even if fullscreen is true, users may want to skip this logic entirely for different reasons, so a new prop for the component would be useful e.g. `disableBodyOverflowEffect` or something similar

**Comment by jaywcjlove** [comment]
Can you provide such an API? I think it might be perfect.

@nuragic Welcome to submit a PR.

```ts
fullscreen?: boolean | 'overflow'
```

**Comment by jaywcjlove** [comment]
oh, I fixed the initial overflow. I don’t know if it has been improved.

@nuragic

**Comment by nuragic** [comment]
Thanks for the quick fix! However, it doesn't solve the issue... I think that we need something like this:
```js
// get the original CSS overflow value for body
const  { overflow } = window.getComputedStyle(document.body, null);
if (fullscreen) {
  document.body.style.overflow = 'hidden';
} else {
  document.body.style.overflow = overflow
}
```

**Comment by jaywcjlove** [comment]
@nuragic In this case, the full screen function is invalid.

**Comment by nuragic** [comment]
@jaywcjlove what do you mean by "invalid"?

**Comment by jaywcjlove** [comment]
If `overflow=hidden` is set, then the overflow obtained by `window.getComputedStyle(document.body, null)` will always be `hidden`

@nuragic

**Comment by nuragic** [comment]
@jaywcjlove yeah, that would make our use case work (the editor is inside a modal, so overflow must be hidden).

**Comment by nuragic** [comment]
@jaywcjlove The PR should be ok, ready for review now, thanks!

**Comment by ZeRego** [comment]
That fix was a good idea but doesn't cover all use cases. We render the markdown input inside a popup which is also manipulating the body overflow value. 

What is happening on opening:
1. popup adds a class to body on open. This class has `overflow: hidden`
2. react-md-editor copies the original value from body which is `overflow: hidden` because of step 1
3. react-md-editor applies `overflow: hidden` to body since `fullscreen` is true

What is happening on closing:
1. popup removes the class from body on close
2. react-md-editor applies the original value `overflow: hidden`


Video of the problem: https://www.loom.com/share/b01f021f25c54312a05ef9907f43b7df

Could we add/remove a class with the overflow style instead of applying it directly ? that way you don't even need to know the original value.

**Comment by jaywcjlove** [comment]
@ZeRego Have you setting `fullscreen` props?

**Comment by ZeRego** [comment]
@jaywcjlove I tried with fullscreen `true` and `false` but doesn't make a difference. 

Your hook is always setting the overflow style independently of the fullscreen value. https://github.com/uiwjs/react-md-editor/blob/master/src%2Fcomponents%2FToolbar%2Findex.tsx#L60

**Comment by jaywcjlove** [comment]
@ZeRego https://codesandbox.io/embed/uiwjs-react-md-editor-issues-309-1rw1le?fontsize=14&hidenavigation=1&theme=dark

I tested it and it looks fine.

**Comment by ZeRego** [comment]
@jaywcjlove Demo of the problem: https://codesandbox.io/s/uiwjs-react-md-editor-issues-309-forked-t23r9h?file=/index.js

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/94a2577b87e1a090a8883eec25f25e08b62d8d87/src/components/Toolbar/index.tsx#L57

Gets the style of the dialog, causing the style to be set incorrectly.

@ZeRego You can add a prop to disable the body styling.

**Comment by ZeRego** [comment]
> Conflicts with Dialog style

Correct, not sure if you saw my initial comment explaining the problem
https://github.com/uiwjs/react-md-editor/issues/309#issuecomment-1061931975

> @ZeRego You can add a prop to disable the body styling.
Are you saying the property `overflow:false` is already supported by react-md-editor ? or asking if it is a good approach ? 
I would prefer if `react-md-editor` could add/remove a class with the styling it needs without relying on the original body style. Or is that hard to implement ?

**Comment by jaywcjlove** [comment]
@ZeRego Upgrade [`v3.10.0`](https://github.com/uiwjs/react-md-editor/releases/tag/v3.10.0)
